server:
  port:8888
  
spring:
  # Spring Cloud Config Server Repository
  cloud:
    config:
      server:
        git: 
        uri: 
        default-label: main
        search-paths:
        - '*service'
          